---
# This playbook is used to update amq63 on your openshift cluster
   #  Usage  ansible-playbook -i hosts update-amq63-templates.yaml
   #                       -e "version=1.4.5" 
  # Sample command line
  #         ansible-playbook -i hosts  update-amq63-templates.yaml -e version=1.4.5 
  #

- hosts: localhost
  vars:
    tplversion:  "{{version|default('1.4.5')}}"
  tasks:



  - name: "Check who am I"
    command: oc whoami
    register: oc_whoami
    ignore_errors: True
    changed_when: false
 
  - fail:
      msg: "This playbook requires to be system:admin"
    when: "oc_whoami.stdout != 'admin' and oc_whoami.stdout != 'system:admin'"


  - name: "Update AMQ template with version :  {{tplversion}} "
    shell: "./scripts/update-amq3-templates.sh {{tplversion}} "
    register: oc_update-amq3_result
 
  - debug:
      var: oc_update-amq3_result
      verbosity: 4






